repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-mysql-exporter
  chart: prometheus-community/prometheus-mysql-exporter
  version: 2.5.3
  values:
    - values.yaml
- name: prometheus-mysql-exporter-component
  chart: ./components