# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mysql-exporter/values.yaml

# Need "exporter" user on Database and necessary privilleges
# NOTE: from mariadb 10.5.9+ need "REPLICA MONITOR" for running "SHOW REPLICA STATUS,"
# CREATE USER 'exporter'@'localhost' IDENTIFIED BY 'XXXXXXXX' WITH MAX_USER_CONNECTIONS 2;
# mysql:  GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'localhost'; FLUSH PRIVILEGES;
# mariadb: GRANT PROCESS, REPLICATION CLIENT, REPLICA MONITOR, SELECT ON *.* TO 'exporter'@'localhost'; FLUSH PRIVILEGES;

mysql:
  # default config
  user: "exporter"
  port: 3306
  additionalConfig:
    - debug
  # associated config file
  existingConfigSecret: 
    name: "prometheus-mysql-exporter-secret"
    key: "my.cnf"

# you can try access /probe before enabled them to Prometheus. by access pod at port 9104.
# EX. http://localhost:9104/probe?target=database.abc.svc.cluster.local:3306&auth_module=client.abc
serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
  multipleTarget:
    enabled: true
    sharedSecret:
      enabled: true # <-- Enable shared credentials for all targets
      name: "shared-auth"
    targets:
      # target connection information with name (required), endpoint (required), port (optional), user(optional), password(optional)
      # each target should be referenced either in targets section or in the associated config file
      - endpoint: mysql1.datbase-namespace.svc.cluster.local
        name: mysql1
      - endpoint: mysql2.datbase-namespace.svc.cluster.local
        name: mysql2
      - endpoint: mysql3.datbase-namespace.svc.cluster.local
        name: mysql3
      - endpoint: mysql4.datbase-namespace.svc.cluster.local
        name: mysql4

tolerations: []
  
affinity: {}