apiVersion: v1
kind: Secret
metadata:
  name: mariadb-galera-secret
type: Opaque
data:
  mariadb-root-password: root_password
  mariadb-galera-mariabackup-password: backup_password
  mariadb-password: password