# kubectl port-forward --namespace kubecost deployment/cost-analyzer 9090

global:
  prometheus:
    enabled: false # to use exists prometheus below
    fqdn: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc:9090
  grafana:
    enabled: false # to use exists grafana below
    domainName: kube-prometheus-stack-grafana.kube-prometheus-stack.svc

serviceMonitor:
  enabled: true
  additionalLabels:
    release:  kube-prometheus-stack
  networkCosts:
    enabled: true
    additionalLabels:
      release:  kube-prometheus-stack
prometheusRule:
  enabled: true
  additionalLabels:
    release:  kube-prometheus-stack

persistentVolume: # app config storage
  size: 5Gi
  dbSize: 5.0Gi
  enabled: true  

tolerations: []
  
affinity: {}

forecasting:
  tolerations: []
    
  affinity: {}
