# WHEN DEPLOY ON AWS EKS
# Use Kubecost provides optimized bundle

# NOTE: spotDataFeed data in bucket can be delete after three days of retention. Athena result are seven days

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model

forecasting:
  fullImageName: public.ecr.aws/kubecost/kubecost-modeling:v0.1.12

networkCosts:
  enabled: true
  image:
    repository: public.ecr.aws/kubecost/kubecost-network-costs

clusterController:
  image:
    repository: public.ecr.aws/kubecost/cluster-controller

# NOTE: For more integration see
# https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations

# Below config are for spot instance only. Cloud Integration can stored as configmap, file or webUI instead of below helm value.
# https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-spot-instances
kubecostProductConfigs:
  spotLabel: eks.amazonaws.com/capacityType
  spotLabelValue: SPOT
  awsSpotDataRegion: ap-southeast-1
  awsSpotDataBucket: spot-datafeed 
  awsSpotDataPrefix: ""
  projectID: "" # AccountID on AWS

serviceAccount:
  create: true  
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXXXXX:role/ROLENAME
