environments:
  aws: {}
  
---
repositories:
- name: apisix
  url: https://charts.apiseven.com

releases:
- name: apisix
  chart: apisix/apisix
  version: 1.11.0
  namespace: ingress-apisix
  values:
    - ./config/apisix/{{ .Environment.Name }}.yaml
- name: components
  chart: ./components