environments:
  default:
    values:
    - environments/default/values.yaml
  aws:
    values:
      - config/apisix/aws.yaml
  
---
repositories:
- name: apisix
  url: https://charts.apiseven.com

releases:
- name: apisix
  chart: apisix/apisix
  version: 1.11.0
  namespace: ingress-apisix
  values:
    - config/apisix/values.yaml
- name: components
  chart: ./components
  namespace: ingress-apisix
  