apiVersion: v1
kind: Secret
metadata:
  name: prometheus-mysql-exporter-secret
type: Opaque
stringData:
  my.cnf: |-
    [client]
    user=NOT_USED
    password=NOT_USED
    # [client.shared-auth]
    # user=exporter
    # password=test
    [client.mysql1]
    user=exporter
    password=secret
    [client.mysql2]
    user=exporter
    password=secret2
    [client.mysql3]
    user=exporter
    password=secret3
    [client.mysql4]
    user=exporter
    password=secret4

# dont forget to apply in kustomize's resources