apiVersion: v1
kind: Secret
metadata:
  name: prometheus-mysql-exporter-secret
type: Opaque
stringData:
  my.cnf: |-
    [client]
    user=NOT_USED
    password=NOT_USED
    [client.shared-auth]
    user=exporter
    password=secret
    [client.mysql1]
    [client.mysql2]
    [client.mysql3]
    [client.mysql4]