# https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix
# when dashboard or ingress-controller enabled, admin.allow.ipList is "0.0.0.0/0"

admin:
  credentials:
    secretName: apisix-credentials

gateway:
  type: NodePort # default

# https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix-dashboard
dashboard:
  enabled: true
  ingress:
    enabled: true
    hosts: 
    - host: apisix-dashboard.local
      paths:
        - /
    className: ""
    annotations: {}
    tls: []
  config:
    authentication:
      users:
        - username: admin
          password: admin

# https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix-ingress-controller
ingress-controller:
  enabled: true
  config:
    apisix:
      existingSecret: apisix-credentials
      existingSecretAdminKeyKey: admin